version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  api:
    build: ./api
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
